# .streamlit/secrets.toml

public_gsheets_url_admitted = "https://docs.google.com/spreadsheets/d/1NbMVLJC2Fg2oPyHxfF7DDqTVYVJ0CrZlExSWaTxI2jU/edit?usp=sharing"

public_gsheets_url_responses = "https://docs.google.com/spreadsheets/d/16lL6LzuhrQXMHZQvNBqvbIfn6yz48AGWPtrCieJ5ylo/edit?usp=sharing"
